spring:
  application:
    name: nyanime
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${nyanime.datasource.host}:${nyanime.datasource.port}/${nyanime.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: ${nyanime.datasource.driver-class-name}
    username: ${nyanime.datasource.username}
    password: ${nyanime.datasource.password}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
springdoc:
  swagger-ui:
    enabled: ${nyanime.swagger.enable}
    path: ${nyanime.swagger.path}
jwt:
  header: Authorization
  secret: "a7309fe8-15df-4b88-a896-35146579e80d"
  expire-time: 86400000