spring:
  application:
    name: nyanime
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${nyanime.datasource.host}:${nyanime.datasource.port}/${nyanime.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: ${nyanime.datasource.driver-class-name}
    username: ${nyanime.datasource.username}
    password: ${nyanime.datasource.password}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
springdoc:
  swagger-ui:
    enabled: ${nyanime.swagger.enable}
    path: ${nyanime.swagger.path}
nyanime:
  jwt:
    header: ${nyanime.jwt.header}
    secret: ${nyanime.jwt.secret}
    expire-time: ${nyanime.jwt.expire-time}